// Generated by CoffeeScript 1.6.3
(function() {
  var number, timer;

  number = 0;

  timer = function() {
    number += 1;
    return $('#test').text(number);
  };

  $(document).ready(function() {
    return setInterval(timer, 1000);
  });

}).call(this);
